import os

F1DATABOT_PLOT_CACHE = os.environ['F1DATABOT_PLOT_CACHE']
F1DATABOT_DATA_CACHE = os.environ["F1DATABOT_DATA_CACHE"]
F1DATABOT_TOKEN = os.environ["F1DATABOT_TOKEN"]
F1DATABOT_ERR_CHANNEL = os.environ["F1DATABOT_ERR_CHANNEL"]

